spring:
  application:
    name: LovableApp
    description: A lovable application for everyone

  datasource:
      url: jdbc:postgresql://localhost:9000/testDB
      username: testUser
      password: password
      driver-class-name: org.postgresql.Driver
  jpa:
      hibernate:
          ddl-auto: update
      show-sql: true
      properties:
          hibernate:
              format_sql: true
              dialect: org.hibernate.dialect.PostgreSQLDialect