spring:
  application:
    name: LovableApp
    description: A lovable application for everyone

  datasource:
      url: jdbc:postgresql://localhost:9000/testDB
      username: testUser
      password: password
      driver-class-name: org.postgresql.Driver
  jpa:
      hibernate:
          ddl-auto: update
      show-sql: true
      properties:
          hibernate:
              format_sql: true
              dialect: org.hibernate.dialect.PostgreSQLDialect
  ai:
    openai:
      api-key:
      base-url: https://openrouter.ai/api
      chat:
        options:
          model: openai/gpt-5.2-codex
          temperature: 0.0
jwt:
  secret-key: as9b7aodlbjfkluosfd789ujeklfnlsduf90b8ha908w74tuqijvlckajdl
stripe:
  api:
    secret: sk_test_51TfyDsCycxLBm9qtxSEARmBGgbraXBR3zqO5Rqm3MDd6UBFJAsfB6NJ8jSDhKvfRIPORa25GIEnF55o1TSW8HNQZ001ylVkPwy
  webhook:
    secret: whsec_4b2418cfe1be80df5a2ae12a4032daff92f35757b8e5ac3685a094ef799aa7c7
client:
  url: http://localhost:3000